"""
Django Admin for the Materials and Vendor masters.

WHAT THIS IS — AND IS NOT
    Scaffolding. It exists so master data can be entered, corrected and checked
    long before the real screens are built. It is NOT the interface designed in
    BOM_Prototype.html — that arrives with the BOM and PO screens.

    Everything here is generated by Django from the models, which is why it
    looks the way it does. It is worth making usable, because this is where the
    data will be maintained for the next few weeks.

EDITING FROM THE LIST
    Fields in `list_editable` can be changed straight from the list, several
    rows at a time, then saved in one go. Much faster than opening 705 materials
    one by one. Everything else is edited by clicking into the record.
"""
from django.contrib import admin
from django.db.models import Count
from django.utils.html import format_html

from .models import (Material, MaterialGroup, UnitOfMeasure, Vendor, VendorCategory,
                     VendorGroup, VendorRate)


@admin.register(MaterialGroup)
class MaterialGroupAdmin(admin.ModelAdmin):
    """The Group master — AG1, PL3, EL2 and the rest."""
    list_display = ("code", "name", "is_stock_item", "material_count")
    list_editable = ("name", "is_stock_item")
    list_display_links = ("code",)
    search_fields = ("code", "name")
    list_filter = ("is_stock_item",)
    ordering = ("code",)

    def get_queryset(self, request):
        # Counted in the database rather than per row, so the page stays fast.
        return super().get_queryset(request).annotate(_materials=Count("materials"))

    @admin.display(description="Materials", ordering="_materials")
    def material_count(self, obj):
        """How many materials sit in this group. A group with 0 can be deleted."""
        return obj._materials


@admin.register(Material)
class MaterialAdmin(admin.ModelAdmin):
    list_display = ("code", "name", "specification", "group", "home_activity", "also_used_in",
                    "uom", "estimation_rate", "gst_percent", "hsn_code", "is_common", "is_active")
    # Everything the data-entry work actually needs, editable straight from the list.
    list_editable = ("specification", "uom", "estimation_rate", "gst_percent",
                     "hsn_code", "is_common", "is_active")
    list_display_links = ("code",)
    # ⚠ Filter on the COLUMNS, not the dead link table. `activity_links` still
    #   exists as a relation but nothing reads it, so filtering by it would
    #   quietly answer a question about data the app has stopped using.
    list_filter = ("group", "uom", "is_common", "is_active", "home_activity")
    search_fields = ("code", "name", "search_aliases", "specification")
    list_per_page = 50
    save_on_top = True
    fieldsets = (
        ("Identity", {
            "fields": ("code", "name", "group", "subgroup", "specification", "search_aliases"),
            "description": "The code is generated as ACTIVITY-GROUP-SERIAL and never changes, "
                           "even if the material is later reclassified.",
        }),
        ("Pricing & tax", {
            "fields": ("uom", "estimation_rate", "gst_percent", "hsn_code"),
            "description": "The estimation rate drives the BOQ and the BOM budget. It is not a "
                           "vendor price — those live on the vendor.",
        }),
        ("Stock", {"fields": ("reorder_level", "current_stock")}),
        ("Status", {
            "fields": ("is_common", "is_active"),
            "description": "Common materials appear in every activity's list, whatever their "
                           "home activity.",
        }),
    )

    def get_queryset(self, request):
        # ⚠ select_related on the COLUMNS, not a prefetch of the dead link table.
        return (super().get_queryset(request)
                .select_related("group", "home_activity", "also_used_in"))

    # ⚠ THERE WAS A METHOD CALLED `home_activity` HERE AND IT HAD TO GO.
    #
    #   It read the old link table and, being a method, it SHADOWED the real
    #   field of the same name added in slice 8. So `list_display` resolved to
    #   the method rather than the column, and every material created after
    #   slice 8 — which has a real home activity and no link row — displayed as
    #   a red "none". The data was right; the screen was reading the wrong place.
    #
    #   Deleting it is the fix: `home_activity` and `also_used_in` are ordinary
    #   foreign keys and Admin renders them without help.


# ⚠ THE VendorCategory INLINE WAS REMOVED FROM VendorAdmin IN SLICE 8.
#   Adding a category from inside a vendor now changes nothing at all — the
#   vendor's `group` is what everything reads. An inline that saves without
#   effect is a worse lie than no inline.


class VendorRateInline(admin.TabularInline):
    model = VendorRate
    extra = 0
    autocomplete_fields = ("material",)


@admin.register(Vendor)
class VendorAdmin(admin.ModelAdmin):
    list_display = ("code", "name", "contact_person", "phone", "whatsapp_number",
                    "gst_number", "is_active")
    list_editable = ("name", "contact_person", "phone", "whatsapp_number",
                     "gst_number", "is_active")
    list_display_links = ("code",)
    # ⚠ Filter on the GROUP, not on the dead category table. Same values, and
    #   this one is a controlled list rather than free text.
    list_filter = ("is_active", "state", "group", "activity_1")
    search_fields = ("code", "name", "contact_person", "phone", "gst_number", "group__name")
    inlines = [VendorRateInline]
    list_per_page = 50
    save_on_top = True
    fieldsets = (
        ("Identity", {"fields": ("code", "name", "contact_person")}),
        ("Contact", {
            "fields": ("phone", "whatsapp_number", "secondary_contact", "secondary_phone", "email"),
            "description": "Leave WhatsApp blank and it fills itself from the phone number "
                           "(91 + a 10-digit mobile). Type one and yours is kept — needed for "
                           "vendors whose main line is a 1800 number, like Schindler and TKE.",
        }),
        ("Tax & terms", {
            "fields": ("gst_number", "state", "address", "payment_terms"),
            "description": "A purchase order cannot legally be issued without a GSTIN. None of "
                           "the 173 vendors has one yet.",
        }),
        ("Status", {"fields": ("is_active",)}),
    )


@admin.register(UnitOfMeasure)
class UnitOfMeasureAdmin(admin.ModelAdmin):
    """
    The unit vocabulary. Editable because it has to be — a unit missing from
    here means somebody's spreadsheet row is rejected and they can do nothing
    about it but telephone you.

    ⚠ The guards live on the model, not here, so they hold for the import and
      any future screen as well: a code cannot change once materials carry it,
      a delete is refused while anything uses it, and a new code close to an
      existing one is refused with the existing one named.
    """
    list_display = ("code", "name", "aliases", "materials_using", "is_active", "sort_order")
    list_editable = ("name", "aliases", "is_active", "sort_order")
    list_display_links = ("code",)
    list_filter = ("is_active",)
    search_fields = ("code", "name", "aliases")
    ordering = ("sort_order", "code")

    @admin.display(description="Materials using it")
    def materials_using(self, unit):
        count = unit.in_use
        return count or format_html('<span style="color:#6B7280">—</span>')


@admin.register(VendorGroup)
class VendorGroupAdmin(admin.ModelAdmin):
    """
    WHAT A VENDOR IS — the master the vendor screen's Group dropdown reads.

    ⚠ THIS IS THE LIVE ONE. `VendorCategory` below it is deliberately NOT
      registered any more; see the note there. Getting these two the wrong way
      round is exactly what happened first: the dead table was editable in
      Admin and this one was not registered at all, so the Master data tile
      pointing at it returned a 404. Found by checking, not by reading.

    ⚠ A GROUP IS NOT AN ACTIVITY. Saahil, after we looked at all 37 old values
      together: "lets use vendor category as an identifier to search vendor …
      lets not mix vendor category and link them to Vendor Activities."

      The list is a mix of material types (Cement, Red Bricks), services
      (Fabricator, Piling), consultants (Structure Engineer) and a utility
      (Torrent Power). It answers WHAT A VENDOR IS, in the words somebody would
      search with. `Vendor.activity_1/2` answers WHICH TRADE THEY SERVE. Two
      questions, two fields, and merging them loses the ability to ask either.
    """
    list_display = ("name", "vendor_count", "is_active")
    list_display_links = ("name",)
    list_editable = ("is_active",)
    search_fields = ("name",)
    ordering = ("name",)

    def get_queryset(self, request):
        # One grouped count, not one query per row.
        return super().get_queryset(request).annotate(n=Count("vendors"))

    @admin.display(description="Vendors", ordering="n")
    def vendor_count(self, group):
        return group.n


# ⚠ `VendorCategory` IS DELIBERATELY NOT REGISTERED, AND MUST NOT BE.
#
#   It is the mechanism VendorGroup replaced: a row per vendor per free-text
#   string, no controlled list, nothing stopping "General Contruction Material"
#   existing on six vendors. The slice 8 migration read its 185 rows once, built
#   the 36-name master out of them, corrected the spellings and set each
#   vendor's group. NOTHING HAS READ IT SINCE.
#
#   Leaving it registered was worse than useless: somebody could open a vendor,
#   add a category, save, and nothing whatsoever would happen — the silent
#   version of the two-places-disagreeing problem that took "Contractor" out of
#   this table in the first place.
#
#   The TABLE and its rows are untouched, so the migration still has something to
#   be checked against. Dropping it is a later migration, once the seed commands
#   and the importer stop referencing it.


@admin.register(VendorRate)
class VendorRateAdmin(admin.ModelAdmin):
    list_display = ("material", "vendor", "rate", "lead_time_days", "is_preferred", "last_updated")
    list_editable = ("rate", "lead_time_days", "is_preferred")
    list_display_links = ("material",)
    list_filter = ("is_preferred", "vendor")
    search_fields = ("material__name", "material__code", "vendor__name")
    autocomplete_fields = ("material", "vendor")


# ⚠ THE MaterialActivity INLINE WAS REMOVED IN SLICE 8, and the machinery that
#   attached it went with it.
#
#   A material's trade is now two columns on the material itself —
#   `home_activity` and `also_used_in` — edited on the material form and on the
#   material's own Admin page. Saahil's instruction: "Material is to be linked to
#   activity in the same material master screen, not as a separate tile."
#
#   Adding a row to MaterialActivity would now change nothing whatsoever, which
#   is why the inline is gone rather than left as a convenience. The table and
#   its 705 rows are untouched, so the migration that copied them still has
#   something to be checked against.
#
#   Its removal also took the cross-app dance with it: masters no longer needs to
#   reach into projects at all, because Activity lives here now.
