# Generated by Django 5.2.16 on 2026-08-14 08:41

import compliance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0010_who_raised_delivered_and_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('applies_to_every_project', models.BooleanField(default=True, help_text='On for a regime nobody can opt out of. Off for one that is ticked per project.')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('one', 'One time'), ('valid', 'Has a validity'), ('repeat', 'Due again each quarter')], default='one', max_length=10)),
                ('validity_days', models.PositiveIntegerField(blank=True, help_text='Typical validity, used to suggest an expiry date. The typed date wins.', null=True)),
                ('is_compulsory', models.BooleanField(default=True, help_text='Off for a document that is good practice rather than required.')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='compliance.compliancetitle')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='compliancetitle',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titles', to='compliance.compliancetype'),
        ),
        migrations.CreateModel(
            name='ProjectCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicable', models.BooleanField(default=True)),
                ('decided_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_decisions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_types', to='projects.project')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_rows', to='compliance.compliancetype')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=compliance.models.compliance_document_path)),
                ('original_name', models.CharField(max_length=200)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('reference', models.CharField(blank=True, help_text='The number on the document, if it has one.', max_length=120)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_uploads', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='compliance.complianceitem')),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
                'indexes': [models.Index(fields=['project', 'item', '-uploaded_at'], name='compliance__project_ece4e6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='complianceitem',
            constraint=models.UniqueConstraint(fields=('title', 'name'), name='one_item_name_per_title'),
        ),
        migrations.AddConstraint(
            model_name='compliancetitle',
            constraint=models.UniqueConstraint(fields=('type', 'name'), name='one_title_name_per_type'),
        ),
        migrations.AddConstraint(
            model_name='projectcompliance',
            constraint=models.UniqueConstraint(fields=('project', 'type'), name='one_row_per_project_type'),
        ),
    ]
