# Generated by Django 5.2.16 on 2026-08-14 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_the_first_draft_checklist'),
        ('projects', '0010_who_raised_delivered_and_paid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='complianceitem',
            name='one_item_name_per_title',
        ),
        migrations.AddField(
            model_name='complianceitem',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Leave empty for every project. Set it for a requirement that applies to one site only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_compliance_items', to='projects.project'),
        ),
        migrations.AddConstraint(
            model_name='complianceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('project', None)), fields=('title', 'name'), name='one_global_item_name_per_title'),
        ),
        migrations.AddConstraint(
            model_name='complianceitem',
            constraint=models.UniqueConstraint(fields=('title', 'name', 'project'), name='one_project_item_name_per_title'),
        ),
    ]
