# Generated by Django 5.0.6 on 2026-08-04 11:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contingency_percent', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=5)),
                ('design_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('saved_at', models.DateTimeField(blank=True, help_text='Exports always use the last saved state.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Rupees per sqft of built-up area', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('basis', models.CharField(blank=True, help_text='Specification assumption shown beside the rate', max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order of work on site')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EstimateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('basis', models.CharField(blank=True, max_length=300)),
                ('is_custom', models.BooleanField(default=False, help_text='Added for this project, not from the company defaults')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='projects.estimate')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. PRJ-001', max_length=12, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('bua_sqft', models.DecimalField(decimal_places=2, help_text='Built-up area including common areas, staircase, lift lobby and mumty', max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('floors', models.CharField(blank=True, help_text='e.g. G+7. Recorded, but does not affect the rate today.', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='estimate',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estimate', to='projects.project'),
        ),
    ]
