"""
Creates the BOM, purchase orders and receipts.

WHAT IS DELIBERATELY ABSENT
    BomLine has no `approved_qty`, `draft_qty` or `received_qty` column.

    Those three figures live in ONE place — the purchase orders — and the BOM
    adds them up when it needs them. Storing them here as well would mean the
    same fact written down twice, and two copies can disagree: a half-finished
    save, a deleted draft, an edited quantity. Every one of those paths simply
    stops existing.

    So BomLine stores only what a person types: planned quantity, site stock,
    threshold, remark, chosen vendor, and an optional order-quantity override.

RECEIPTS ARE THEIR OWN TABLE
    Rather than a "received" number on the PO line, so partial deliveries are
    recorded honestly — 300 today, 200 next week, each with its own date —
    instead of one figure edited twice. It is also the connection point for the
    future task management module.
"""
# Originally generated by Django 5.2.16 on 2026-08-05 22:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_material_uom'),
        ('projects', '0003_seed_activity_master'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boms_generated', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='projects.project')),
            ],
            options={
                'verbose_name': 'BOM',
                'verbose_name_plural': 'BOMs',
            },
        ),
        migrations.CreateModel(
            name='BomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, help_text='Tells duplicate lines apart, e.g. "footing & plinth" vs "slab pour 2".', max_length=200)),
                ('planned_qty', models.DecimalField(decimal_places=3, default=0, help_text='How much this project needs. The BOQ carries money only, never quantities.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_qty', models.DecimalField(decimal_places=3, default=0, help_text='What is on site now. Entered or bulk-uploaded, never calculated.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_qty', models.DecimalField(decimal_places=3, default=0, help_text='Reorder threshold. Below this the line is flagged.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('order_qty_override', models.DecimalField(blank=True, decimal_places=3, help_text='Leave blank to use the suggested quantity. Type a number to override it — ordering 20 of a planned 150 is normal, and so is ordering extra.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('vendor_rate', models.DecimalField(blank=True, decimal_places=2, help_text="Pre-filled from the vendor's rate, editable. Blank falls back to the material's estimation rate.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='projects.activity')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='projects.bom')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='masters.material')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='masters.vendor')),
            ],
            options={
                'ordering': ['activity__sort_order', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Auto-generated, e.g. PO-0001', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('delivered', 'Delivered'), ('paid', 'Paid')], default='draft', max_length=10)),
                ('raised_on', models.DateField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('vendor_gstin', models.CharField(blank=True, max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_approved', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='projects.project')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='masters.vendor')),
            ],
            options={
                'ordering': ['-raised_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bom_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='projects.bomline')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='projects.purchaseorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('received_on', models.DateField()),
                ('source', models.CharField(choices=[('manual', 'Marked delivered by hand'), ('task', 'Task management module')], default='manual', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='projects.purchaseorderline')),
            ],
            options={
                'ordering': ['-received_on', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='bomline',
            index=models.Index(fields=['bom', 'activity'], name='projects_bo_bom_id_9be3fd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['project', 'vendor'], name='projects_pu_project_f761eb_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='projects_pu_status_52fafd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['bom_line'], name='projects_pu_bom_lin_b5650f_idx'),
        ),
    ]
