# Generated by Django 5.2.16 on 2026-09-10 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_who_raised_delivered_and_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="dlp_months",
            field=models.PositiveSmallIntegerField(
                default=12,
                help_text="Defect liability period, months from the final bill's approval.",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="mobilisation_advance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Advance agreed on the work order, recovered pro rata from each RA bill.",
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="retention_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                help_text="Held back from every RA bill, on the work value (ex-GST). Work orders only.",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Marked delivered by hand"),
                    ("task", "Task management module"),
                    ("rabill", "Certified on an RA bill"),
                ],
                default="manual",
                max_length=10,
            ),
        ),
    ]
