"""
Help text only — "trade" now reads "construction activity" on the material form.

⚠ NO SCHEMA CHANGE. Django records help_text in migration state, so a wording
  change to a field still produces a file. Nothing about the column moves.
"""
# Generated by Django 5.2.16 on 2026-08-14 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_alter_activity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='home_activity',
            field=models.ForeignKey(help_text='The construction activity this material belongs to. Required.', on_delete=django.db.models.deletion.PROTECT, related_name='home_materials', to='masters.activity'),
        ),
    ]
