# Generated by Django 5.2.16 on 2026-09-10 06:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masters", "0014_material_estimation_rate_help_text"),
        ("projects", "0011_work_order_terms"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RABill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="RA-000001, from NumberSeries",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                ("bill_date", models.DateField()),
                (
                    "contractor_ref",
                    models.CharField(
                        blank=True, help_text="Their invoice number.", max_length=60
                    ),
                ),
                ("period_from", models.DateField(blank=True, null=True)),
                ("period_to", models.DateField(blank=True, null=True)),
                ("is_final", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("certified", "Certified"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("certified_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ra_bills_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "certified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ra_bills_certified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ra_bills_raised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ra_bills",
                        to="projects.purchaseorder",
                    ),
                ),
            ],
            options={
                "ordering": ["purchase_order_id", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="RABillLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "claimed_qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "certified_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("gst_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "discount_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("remark", models.CharField(blank=True, max_length=200)),
                (
                    "po_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ra_bill_lines",
                        to="projects.purchaseorderline",
                    ),
                ),
                (
                    "ra_bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finance.rabill",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RetentionRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("released_on", models.DateField()),
                ("reference", models.CharField(blank=True, max_length=60)),
                ("note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retention_releases",
                        to="projects.purchaseorder",
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retention_released",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["released_on", "id"],
            },
        ),
        migrations.CreateModel(
            name="VendorInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="VB-000001, our reference", max_length=20, unique=True
                    ),
                ),
                ("vendor_invoice_no", models.CharField(max_length=60)),
                ("invoice_date", models.DateField()),
                (
                    "taxable",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "gst",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_invoices",
                        to="projects.purchaseorder",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_invoices_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-invoice_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VendorPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(help_text="PV-000001", max_length=20, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("advance", "Advance"),
                            ("against_invoice", "Against invoice"),
                            ("ra_bill", "RA bill"),
                            ("retention_release", "Retention release"),
                        ],
                        max_length=20,
                    ),
                ),
                ("paid_on", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tds_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("neft", "NEFT / RTGS"),
                            ("cheque", "Cheque"),
                            ("upi", "UPI"),
                            ("cash", "Cash"),
                            ("other", "Other"),
                        ],
                        default="neft",
                        max_length=10,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, help_text="UTR, cheque number…", max_length=60
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="projects.purchaseorder",
                    ),
                ),
                (
                    "ra_bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.rabill",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_payments_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="masters.vendor",
                    ),
                ),
                (
                    "vendor_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.vendorinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_on", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="rabill",
            index=models.Index(fields=["status"], name="finance_rab_status_6f1801_idx"),
        ),
        migrations.AddConstraint(
            model_name="rabill",
            constraint=models.UniqueConstraint(
                fields=("purchase_order", "sequence"),
                name="finance_one_sequence_per_wo",
            ),
        ),
        migrations.AddConstraint(
            model_name="rabillline",
            constraint=models.UniqueConstraint(
                fields=("ra_bill", "po_line"),
                name="finance_one_line_per_po_line_per_bill",
            ),
        ),
        migrations.AddIndex(
            model_name="vendorpayment",
            index=models.Index(
                fields=["purchase_order", "kind"], name="finance_ven_purchas_bfa5e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorpayment",
            index=models.Index(
                fields=["paid_on"], name="finance_ven_paid_on_f28b20_idx"
            ),
        ),
    ]
