# Generated by Django 5.0.6 on 2026-08-04 11:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. CEM', max_length=4, unique=True)),
                ('name', models.CharField(help_text='e.g. Cement & Binders', max_length=60)),
                ('is_stock_item', models.BooleanField(default=True, help_text='Off for services like Site Expense and Transport — orderable, but never held in stock.')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. VEN-001', max_length=12, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(help_text="Digits only. This is the vendor's identity — never dedupe by name.", max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d*$', 'Digits only — no spaces, plus signs or dashes.')])),
                ('whatsapp_number', models.CharField(blank=True, help_text='91 + 10 digits. Blank for landlines and 1800 numbers.', max_length=15, validators=[django.core.validators.RegexValidator('^\\d*$', 'Digits only — no spaces, plus signs or dashes.')])),
                ('secondary_contact', models.CharField(blank=True, max_length=120)),
                ('secondary_phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d*$', 'Digits only — no spaces, plus signs or dashes.')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gst_number', models.CharField(blank=True, help_text='Captured on the first purchase order. Editable only here.', max_length=15, validators=[django.core.validators.RegexValidator('^$|^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1}$', 'A GSTIN is 15 characters, e.g. 24ABCDE1234F1Z5.')])),
                ('state', models.CharField(blank=True, help_text='Derived from the first 2 digits of the GSTIN.', max_length=60)),
                ('address', models.TextField(blank=True)),
                ('payment_terms', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='GROUP-SUBGROUP-SERIAL, e.g. CEM-OPC-001', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('subgroup', models.CharField(default='GEN', max_length=6)),
                ('specification', models.CharField(blank=True, max_length=300)),
                ('uom', models.CharField(choices=[('Nos', 'Nos'), ('Set', 'Set'), ('Pair', 'Pair'), ('Bag', 'Bag'), ('Packet', 'Packet'), ('Box', 'Box'), ('Tin', 'Tin'), ('Bottle', 'Bottle'), ('Bundle', 'Bundle'), ('Drum', 'Drum'), ('Kg', 'Kg'), ('Ton', 'Ton'), ('Litre', 'Litre'), ('Metre', 'Metre'), ('Rft', 'Rft'), ('Sqft', 'Sqft'), ('Sqm', 'Sqm'), ('Cum', 'Cum'), ('Tractor', 'Tractor'), ('Trip', 'Trip'), ('Job', 'Job'), ('Hour', 'Hour'), ('Day', 'Day'), ('Month', 'Month'), ('Lumpsum', 'Lumpsum'), ('House', 'House')], max_length=20)),
                ('estimation_rate', models.DecimalField(decimal_places=2, default=0, help_text='Drives the BOQ. Not a vendor price.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('hsn_code', models.CharField(blank=True, help_text='Filled on first use. Required on a GST invoice.', max_length=10)),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('search_aliases', models.CharField(blank=True, help_text='Site vocabulary — "saria" finds TMT bar, "chips" finds aggregate.', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='masters.materialgroup')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='masters.vendor')),
            ],
            options={
                'verbose_name_plural': 'vendor categories',
            },
        ),
        migrations.CreateModel(
            name='VendorRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_rates', to='masters.material')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='masters.vendor')),
            ],
            options={
                'ordering': ['material', 'rate'],
            },
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['name'], name='masters_mat_name_90d37c_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['group', 'subgroup'], name='masters_mat_group_i_44fcd5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorcategory',
            unique_together={('vendor', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='vendorrate',
            unique_together={('vendor', 'material')},
        ),
    ]
