"""
Adds KW and MT to the allowed units, so the master data imports cleanly.

WHY THESE TWO
    KW  — SOLAR PANEL is quoted in kilowatts. Nothing existing means the same.
    MT  — steel is planned, bought and paid for in metric tonnes.

"Hrs" is deliberately NOT added. The list already has "Hour", and two spellings
of one unit in a dropdown means two people record the same thing differently and
hours never total correctly. Spreadsheet spellings are translated instead — see
UOM_ALIASES in masters/models.py.

Choices are not enforced by the database, only by forms and validation, so this
migration changes no stored data.
"""
# Generated by Django 5.2.16 on 2026-08-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_material_is_common'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='uom',
            field=models.CharField(choices=[('Nos', 'Nos'), ('Set', 'Set'), ('Pair', 'Pair'), ('Bag', 'Bag'), ('Packet', 'Packet'), ('Box', 'Box'), ('Tin', 'Tin'), ('Bottle', 'Bottle'), ('Bundle', 'Bundle'), ('Drum', 'Drum'), ('Kg', 'Kg'), ('Ton', 'Ton'), ('MT', 'MT'), ('Litre', 'Litre'), ('Metre', 'Metre'), ('Rft', 'Rft'), ('Sqft', 'Sqft'), ('Sqm', 'Sqm'), ('Cum', 'Cum'), ('Tractor', 'Tractor'), ('Trip', 'Trip'), ('Job', 'Job'), ('Hour', 'Hour'), ('Day', 'Day'), ('Month', 'Month'), ('Lumpsum', 'Lumpsum'), ('House', 'House'), ('KW', 'KW')], max_length=20),
        ),
    ]
