# Generated by Django 5.2.16 on 2026-08-15 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_materialgroup_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_key', models.CharField(max_length=40)),
                ('step_label', models.CharField(max_length=40)),
                ('gujarati', models.TextField(blank=True)),
                ('source_english', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['panel_key', 'step_label'],
                'constraints': [models.UniqueConstraint(fields=('panel_key', 'step_label'), name='one_translation_per_step')],
            },
        ),
    ]
