# Generated by Django 5.2.16 on 2026-09-10 06:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masters", "0014_material_estimation_rate_help_text"),
        ("projects", "0010_who_raised_delivered_and_paid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Architect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("firm", models.CharField(blank=True, max_length=160)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d*$",
                                "Digits only — no spaces, plus signs or dashes.",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DrawingGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Up to four capitals, e.g. ARC. Shown on the register.",
                        max_length=4,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Drawing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="The architect's drawing number, as printed.",
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("required_by", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "architect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drawings",
                        to="drawings.architect",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drawings_registered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drawings",
                        to="projects.project",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drawings",
                        to="drawings.drawinggroup",
                    ),
                ),
            ],
            options={
                "ordering": ["group__sort_order", "group__code", "number"],
            },
        ),
        migrations.CreateModel(
            name="DrawingRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="As the architect labels it — R0, R1, R2.",
                        max_length=12,
                    ),
                ),
                ("file", models.FileField(upload_to="drawings/%Y/%m/")),
                ("original_name", models.CharField(max_length=200)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                (
                    "received_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("approved_on", models.DateField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drawing_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drawing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="drawings.drawing",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drawing_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Transmittal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=12, unique=True)),
                (
                    "issued_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("construction", "For construction"),
                            ("approval", "For approval"),
                            ("information", "For information"),
                        ],
                        default="construction",
                        max_length=12,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transmittals_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transmittals",
                        to="projects.project",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transmittals",
                        to="masters.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TransmittalLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transmittal_lines",
                        to="drawings.drawingrevision",
                    ),
                ),
                (
                    "transmittal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="drawings.transmittal",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "revision__drawing__group__sort_order",
                    "revision__drawing__number",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="drawing",
            constraint=models.UniqueConstraint(
                fields=("project", "number"), name="one_drawing_number_per_project"
            ),
        ),
        migrations.AddIndex(
            model_name="drawingrevision",
            index=models.Index(
                fields=["drawing", "-uploaded_at"],
                name="drawings_dr_drawing_b33303_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="drawingrevision",
            constraint=models.UniqueConstraint(
                fields=("drawing", "label"), name="one_label_per_drawing"
            ),
        ),
        migrations.AddConstraint(
            model_name="transmittalline",
            constraint=models.UniqueConstraint(
                fields=("transmittal", "revision"), name="one_revision_per_transmittal"
            ),
        ),
    ]
