# Generated by Django 5.2.16 on 2026-09-10 06:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0010_who_raised_delivered_and_paid"),
        ("tasks", "0003_delete_milestone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "phone",
                    models.CharField(
                        help_text="Digits only. This is the customer's identity.",
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d*$",
                                "Digits only — no spaces, plus signs or dashes.",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "pan",
                    models.CharField(
                        blank=True,
                        help_text="Needed on the agreement and for TDS. Upper case.",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^$|^[A-Z]{5}[0-9]{4}[A-Z]$",
                                "A PAN is 10 characters, e.g. ABCDE1234F.",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=12, unique=True)),
                ("booked_on", models.DateField()),
                (
                    "agreement_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "gst_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5"),
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("booked", "Booked"),
                            ("agreement", "Agreement"),
                            ("registered", "Registered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="booked",
                        max_length=12,
                    ),
                ),
                ("agreement_on", models.DateField(blank=True, null=True)),
                ("registered_on", models.DateField(blank=True, null=True)),
                ("cancelled_on", models.DateField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, max_length=300)),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="sales.customer",
                    ),
                ),
                (
                    "transferred_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings_transferred_away",
                        to="sales.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-booked_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BookingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("booked", "Booked"),
                            ("agreement", "Agreement signed"),
                            ("registered", "Registered"),
                            ("cancelled", "Cancelled"),
                            ("transferred", "Transferred"),
                            ("demand", "Demand raised"),
                            ("receipt", "Receipt recorded"),
                            ("schedule", "Schedule changed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=300)),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="sales.booking",
                    ),
                ),
                (
                    "by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Demand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=12, unique=True)),
                ("raised_on", models.DateField()),
                ("due_on", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "gst_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5"), max_digits=5
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demands",
                        to="sales.booking",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demands_raised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["raised_on", "id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=12, unique=True)),
                ("received_on", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("cheque", "Cheque"),
                            ("neft", "NEFT / RTGS"),
                            ("upi", "UPI"),
                            ("cash", "Cash"),
                            ("other", "Other"),
                        ],
                        default="neft",
                        max_length=10,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Cheque number, UTR, UPI reference.",
                        max_length=120,
                    ),
                ),
                (
                    "tds_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="sales.booking",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_receipts_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "demand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="sales.demand",
                    ),
                ),
            ],
            options={
                "ordering": ["received_on", "id"],
            },
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d*$",
                                "Digits only — no spaces, plus signs or dashes.",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("walkin", "Walk-in"),
                            ("referral", "Referral"),
                            ("broker", "Broker"),
                            ("portal", "Portal"),
                            ("hoarding", "Hoarding"),
                            ("other", "Other"),
                        ],
                        default="walkin",
                        max_length=10,
                    ),
                ),
                ("broker_name", models.CharField(blank=True, max_length=120)),
                (
                    "interested_in",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1bhk", "1 BHK"),
                            ("2bhk", "2 BHK"),
                            ("3bhk", "3 BHK"),
                            ("4bhk", "4 BHK"),
                            ("penthouse", "Penthouse"),
                            ("shop", "Shop"),
                            ("office", "Office"),
                            ("other", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("visited", "Visited"),
                            ("negotiating", "Negotiating"),
                            ("booked", "Booked"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=12,
                    ),
                ),
                ("lost_reason", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enquiries",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "enquiries",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="enquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="sales.enquiry",
            ),
        ),
        migrations.CreateModel(
            name="PaymentMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=120)),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("due_on", models.DateField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="sales.booking",
                    ),
                ),
                (
                    "task_header",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_milestones",
                        to="tasks.taskheader",
                    ),
                ),
            ],
            options={
                "ordering": ["booking", "sequence", "id"],
            },
        ),
        migrations.AddField(
            model_name="demand",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demands",
                to="sales.paymentmilestone",
            ),
        ),
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visited_on", models.DateField()),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="sales.enquiry",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_visits_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-visited_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(help_text='e.g. "A-101".', max_length=20)),
                ("block", models.CharField(blank=True, max_length=20)),
                ("floor", models.IntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("1bhk", "1 BHK"),
                            ("2bhk", "2 BHK"),
                            ("3bhk", "3 BHK"),
                            ("4bhk", "4 BHK"),
                            ("penthouse", "Penthouse"),
                            ("shop", "Shop"),
                            ("office", "Office"),
                            ("other", "Other"),
                        ],
                        default="2bhk",
                        max_length=12,
                    ),
                ),
                (
                    "carpet_sqft",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "saleable_sqft",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="units",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "block", "floor", "number"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="sales.unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                fields=("project", "number"), name="one_unit_number_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "cancelled"), _negated=True),
                fields=("unit",),
                name="one_live_booking_per_unit",
            ),
        ),
    ]
